--------------------------------------------------------
--  File created - péntek-május-12-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object GYEREK with DBMS_METADATA attempting internal generator.


CREATE TABLE GYEREK 
(
  ID NUMBER(4, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL 
, NEV VARCHAR2(32 BYTE) NOT NULL 
, NEM VARCHAR2(1 BYTE) 
, ISKOLAS NUMBER(1, 0) DEFAULT 1 
, KOR NUMBER(2, 0) 
, FELVITTE VARCHAR2(16 BYTE) DEFAULT USER NOT NULL 
, FELVITEL DATE DEFAULT SYSDATE NOT NULL 
);

ALTER TABLE GYEREK
ADD CONSTRAINT SYS_C0045504 CHECK 
(nem IN ('F','L')); 

ALTER TABLE GYEREK
ADD CONSTRAINT SYS_C0045505 CHECK 
(iskolas IN(0,1));

ALTER TABLE GYEREK
ADD CONSTRAINT SYS_C0045506 PRIMARY KEY 
(
  ID 
);

CREATE UNIQUE INDEX SYS_C0045506 ON GYEREK (ID ASC);

REM INSERTING into GYEREK
SET DEFINE OFF;
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('7','Nina','L','1',null,'OKT_SKITTI',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('8','Kitti','L','1',null,'OKT_SKITTI',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('1','Gábor','F','0',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('2','Ottó',null,'1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('3','Pisti','F','1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('4','Gábor','F','0',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('5','Ottó',null,'1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('6','Pisti','F','1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('9','Gabriella','L','1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('10','Péter','F','1','5','GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('11','Gabriella','L','1',null,'GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
Insert into GYEREK (ID,NEV,NEM,ISKOLAS,KOR,FELVITTE,FELVITEL) values ('12','Péter','F','1','5','GI17_BHG',to_date('17-MÁJ.  -03','RR-MON-DD'));
commit;
-- Unable to render INDEX DDL for object SYS_C0045506 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C0045506 ON GYEREK (ID ASC);