--------------------------------------------------------
--  File created - péntek-május-12-2017   
--------------------------------------------------------
-- Unable to render TABLE DDL for object KOLCSONZO with DBMS_METADATA attempting internal generator.

CREATE TABLE KOLCSONZO 
(
  KID NUMBER(4, 0) GENERATED BY DEFAULT AS IDENTITY NOT NULL 
, NEV VARCHAR2(40 BYTE) 
, NEM VARCHAR2(1 BYTE) 
, SZULDAT DATE 
, BEIRATKOZAS DATE 
, VIP NUMBER(1, 0) 
);

CREATE UNIQUE INDEX SYS_C0026317 ON KOLCSONZO (KID ASC);

ALTER TABLE KOLCSONZO
ADD CONSTRAINT SYS_C0026317 PRIMARY KEY 
(
  KID 
);

ALTER TABLE KOLCSONZO
ADD CONSTRAINT SYS_C0031861 FOREIGN KEY
(
  NEM 
)
REFERENCES NEM
(
  KOD 
);

REM INSERTING into KOLCSONZO
SET DEFINE OFF;
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('1','Bana Árpádné','N',to_date('67-JÚL.  -21','RR-MON-DD'),to_date('04-JÚN.  -24','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('2','Szabó Lajosné','N',to_date('58-OKT.  -29','RR-MON-DD'),to_date('04-AUG.  -25','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('3','Pordán Gyöngyi','N',to_date('54-SZEPT.-08','RR-MON-DD'),to_date('11-DEC.  -09','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('4','Szerdahelyi Adél','N',to_date('60-DEC.  -23','RR-MON-DD'),to_date('08-SZEPT.-01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('5','Rezes Andrásné','N',to_date('73-MÁRC. -27','RR-MON-DD'),to_date('03-JÚL.  -25','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('6','Babos Krisztina','N',to_date('67-NOV.  -18','RR-MON-DD'),to_date('07-ÁPR.  -06','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('7','Máriás Károly','F',to_date('51-JAN.  -13','RR-MON-DD'),to_date('13-JÚL.  -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('8','Mikó Annamária','N',to_date('72-AUG.  -09','RR-MON-DD'),to_date('12-OKT.  -11','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('9','Solymosi Andrásné','N',to_date('67-NOV.  -29','RR-MON-DD'),to_date('11-AUG.  -07','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('10','Várhegyi Krisztina','N',to_date('64-OKT.  -06','RR-MON-DD'),to_date('11-AUG.  -12','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('11','Kovácsné Brigitta','N',to_date('78-MÁRC. -29','RR-MON-DD'),to_date('13-OKT.  -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('12','Papp Kázmér','F',to_date('72-OKT.  -16','RR-MON-DD'),to_date('04-AUG.  -31','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('13','Teleki Annamária','N',to_date('68-OKT.  -03','RR-MON-DD'),to_date('10-NOV.  -13','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('14','Kovács Adél','N',to_date('86-SZEPT.-09','RR-MON-DD'),to_date('11-SZEPT.-17','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('15','Papp Kornélia','N',to_date('66-JÚN.  -01','RR-MON-DD'),to_date('03-NOV.  -03','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('16','Vojevogyina Alíz','N',to_date('52-JAN.  -17','RR-MON-DD'),to_date('10-MÁRC. -22','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('17','Tóth Ferenc','F',to_date('54-AUG.  -26','RR-MON-DD'),to_date('03-AUG.  -14','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('18','Kovács Adél','N',to_date('79-ÁPR.  -29','RR-MON-DD'),to_date('07-OKT.  -13','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('19','Karajos Alexa','N',to_date('65-DEC.  -04','RR-MON-DD'),to_date('07-FEBR. -20','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('20','Várkonyi Miklósné','N',to_date('77-JÚN.  -18','RR-MON-DD'),to_date('11-SZEPT.-20','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('21','Fodor Emília','N',to_date('78-OKT.  -13','RR-MON-DD'),to_date('13-SZEPT.-28','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('22','Papcsák Adonisz','F',to_date('74-MÁRC. -22','RR-MON-DD'),to_date('10-FEBR. -16','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('23','Mester Tiborné','N',to_date('53-ÁPR.  -20','RR-MON-DD'),to_date('05-OKT.  -23','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('24','Vidák Áron','F',to_date('91-OKT.  -28','RR-MON-DD'),to_date('03-MÁJ.  -19','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('25','Kiss Gergely','F',to_date('47-AUG.  -23','RR-MON-DD'),to_date('07-JÚL.  -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('26','Mizi Krisztina','N',to_date('70-SZEPT.-20','RR-MON-DD'),to_date('09-ÁPR.  -28','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('27','Szerdahelyi Kriszta','N',to_date('86-MÁJ.  -17','RR-MON-DD'),to_date('06-NOV.  -15','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('28','Krausz Attiláné','N',to_date('91-JÚL.  -27','RR-MON-DD'),to_date('13-JAN.  -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('29','Lipcsei Rita','N',to_date('87-MÁJ.  -20','RR-MON-DD'),to_date('09-NOV.  -21','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('30','Szántó Károly','F',to_date('62-JÚL.  -14','RR-MON-DD'),to_date('11-OKT.  -22','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('31','Bukovics Erika','N',to_date('81-JAN.  -17','RR-MON-DD'),to_date('10-MÁJ.  -01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('32','Érdi László','F',to_date('89-MÁJ.  -31','RR-MON-DD'),to_date('04-NOV.  -15','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('33','Kiss Gergely','F',to_date('76-ÁPR.  -24','RR-MON-DD'),to_date('11-JAN.  -19','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('34','Egressy István','F',to_date('64-AUG.  -31','RR-MON-DD'),to_date('14-JAN.  -31','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('35','Pettendi Csaba','F',to_date('79-AUG.  -01','RR-MON-DD'),to_date('11-MÁJ.  -09','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('36','Fekete Liza','N',to_date('68-JAN.  -22','RR-MON-DD'),to_date('11-OKT.  -28','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('37','Joó Mária','N',to_date('56-MÁJ.  -06','RR-MON-DD'),to_date('06-SZEPT.-09','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('38','Koós Alajos','F',to_date('90-DEC.  -14','RR-MON-DD'),to_date('13-NOV.  -16','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('39','Kerekes Zsombor','F',to_date('71-NOV.  -13','RR-MON-DD'),to_date('03-JÚL.  -07','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('40','Komondi Aletta','N',to_date('71-MÁJ.  -02','RR-MON-DD'),to_date('11-DEC.  -23','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('41','Mizi Marietta','N',to_date('48-JÚL.  -30','RR-MON-DD'),to_date('12-JÚN.  -21','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('42','Álmosdi Tibor','F',to_date('89-AUG.  -31','RR-MON-DD'),to_date('12-MÁRC. -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('43','Kerezsi Anita','N',to_date('57-SZEPT.-22','RR-MON-DD'),to_date('10-OKT.  -01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('44','Kassai Jánosné','N',to_date('60-DEC.  -26','RR-MON-DD'),to_date('05-AUG.  -12','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('45','Pongrácz Zoltánné','N',to_date('54-MÁRC. -11','RR-MON-DD'),to_date('11-NOV.  -01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('46','Keresztes Tibor','F',to_date('54-OKT.  -17','RR-MON-DD'),to_date('05-JÚL.  -09','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('47','Kiss Hedvig','N',to_date('49-FEBR. -08','RR-MON-DD'),to_date('12-NOV.  -23','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('48','Rõthné Éva','N',to_date('54-JÚL.  -25','RR-MON-DD'),to_date('12-AUG.  -19','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('49','Pászti Annamária','N',to_date('78-JÚL.  -28','RR-MON-DD'),to_date('07-MÁRC. -29','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('50','MOLNÁRNÉ Júlia','N',to_date('47-JÚL.  -21','RR-MON-DD'),to_date('13-AUG.  -10','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('51','Erõs Andrea','N',to_date('78-JÚN.  -28','RR-MON-DD'),to_date('11-MÁJ.  -18','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('52','Asztalos Ádám','F',to_date('48-MÁJ.  -06','RR-MON-DD'),to_date('12-MÁRC. -07','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('53','Eszes Krisztina','N',to_date('61-JÚN.  -11','RR-MON-DD'),to_date('11-NOV.  -11','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('54','Kovács Marianna','N',to_date('60-JÚL.  -03','RR-MON-DD'),to_date('08-AUG.  -03','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('55','Kovács Gézáné','N',to_date('55-JÚN.  -27','RR-MON-DD'),to_date('09-MÁJ.  -14','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('56','Szabó Ákosné','N',to_date('79-JÚL.  -10','RR-MON-DD'),to_date('06-FEBR. -01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('57','Nagy-Szántó Anna','N',to_date('91-MÁJ.  -07','RR-MON-DD'),to_date('13-ÁPR.  -25','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('58','Kerek Gábor','F',to_date('61-NOV.  -04','RR-MON-DD'),to_date('03-NOV.  -19','RR-MON-DD'),'1');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('59','Kocsis Krisztián','F',to_date('74-JÚN.  -11','RR-MON-DD'),to_date('07-ÁPR.  -01','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('60','Veres Adrián','F',to_date('77-OKT.  -20','RR-MON-DD'),to_date('11-JÚN.  -16','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('61','Kiss Laura','N',to_date('78-JÚN.  -28','RR-MON-DD'),to_date('07-MÁRC. -29','RR-MON-DD'),'0');
Insert into KOLCSONZO (KID,NEV,NEM,SZULDAT,BEIRATKOZAS,VIP) values ('62','Good Henrik','F',to_date('49-FEBR. -08','RR-MON-DD'),to_date('02-JAN.  -01','RR-MON-DD'),'1');
commit;
-- Unable to render INDEX DDL for object SYS_C0026317 with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX SYS_C0026317 ON KOLCSONZO (KID ASC);

